---
title: Introducción

subtitle: "¿Cuál es el secreto de la felicidad?"

author: "Javiera Valenzuela Soto"

output: html_document
---

En este útlimo tiempo, el concepto de felicidad y bienestar de las personas se ha ido extendiendo a diversos campos, en donde está sonando fuerte en materias como economía y políticas públicas.

Sin embargo, no es sencillo definir el concepto de bienestar o felicidad, los cuales tienden a estar relacionados.\
Científicamente, se suele entender el concepto de Felicidad como "la experiencia de bienestar que se asocia a una profunda satisfacción y sensación de propósito vital" (CLARÍN, 06/12/2017). Con lo anterior en mente, podríamos utilizar esta terminología como una unidad de medida para cuantificar el grado de satisfacción de cada persona con su estilo de vida. [La Vanguardia](https://www.lavanguardia.com/vivo/psicologia/20171206/433415391204/claves-felicidad-ciencia.html).

Desde el año 2012, las naciones unidad lanzaron un programa llamada "Informe de Felicidad Mundial (World Happiness Report), en donde mediante la encuesta Gallup comenzó a evaluar el bienestar de casi todos los países bajo los siguientes factores que pueden influir en los niveles de felicidad en el mundo: apoyo social, dinero, salud, libertad, confianza y bondad. [El mundo](https://www.elmundo.es/vida-sana/bienestar/2018/01/29/5a6b3844468aebfb388b4601.html).

Debido a esta encuesta y sus resultados, comienzan a surgir interrogantes como: ¿Cuáles son los países que se consideran más felices?, ¿Qué tienen en común las personas más felices del mundo? y ¿En qué se puede trabajar y mejorar para ser más felices?

Por lo anterior, el siguiente informe tiene como objetivo entender cuáles son las variables que más pueden influir en la felicidad y bienestar percibido por individuos de distintos países, qué es lo que poseen en común los países más felices y en qué suelen diferenciarse con los menos felices. Además, intentaremos analizar cómo la pandemia ha incidido en los niveles de felicidad percibidos por la población, y así ver si encontramos un patrón entre la incidencia del COVID-19 y el nivel de felicidad de los países en el mundo.

Este trabajo contará con 4 repositorios, en donde mediante gráficos y modelos de regresión intentaremos responder las siguientes preguntas:

-   ¿Cuáles son los países con el mayor y menor índice de felicidad en el mundo?

-   ¿Qué similitudes y diferencias comparten esos países?

-   ¿Cómo ha incidido el COVID-19 mediante la mortalidad de esos países?

-   En los países más felices, ¿Existe una mayor igualdad y libertad de género?

-   ¿El dinero realmente hace la felicidad o influyen otras variables?

Por último, se intentará responder la pregunta quen planteamos más arriba; ¿Cuál es el secreto de la felicidad? Es decir, ¿En qué podemos trabajar y así aumentar la percepción de felicidad en las personas? Para ello, en el repositorio correspondiente al data set definiremos las variables y sus índicadores de medida, para luego comenzar un manejo de datos que se explicitará en los repositorios "productos-resultados" y "gráficos", y así concluir con ideas para trabajar en cómo mejorar la felicidad de las personas en el mundo.
